<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bomberman.Core\Bomberman.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bomberman.Rollback\Bomberman.Rollback.csproj" />
  </ItemGroup>

</Project>
